### ISSUE TITLE
Error message on sample dataset with standard conditions

### ISSUE THREAD

**Issue by SamN1985** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#5]
Hi guys
Great package. Encountering an issue on stage 3 of the pipeline with the training data/images. 

Error message is as follows "No Window with the title "Neurone_1_Neurite11" found."

An RoiSet is produced, as are Stack_Body, Stack_BodySkelet, Stack_Neuron_Bin, Stack_Neuron_Original and Stack_NoBodySkelet files.

Log file contains the following

C:\Users\NAME\Desktop\NAME\AutoneuriteJ\resultats_AutoneuriteJ\r_Neuron_Demo-Image_Neurons_Cy3\

 AutoNeuriteJ_Part III_settings : 
 minimal size of Axons (in pixels)=150
minimal size of Neurites (in pixels)=15
Axonal size ratio=1.5
Neurite Order : 1=axon / 2=primary neurite / 3=secondary neurite / 4=tertiary neurite ...

 Measures : 
Neuron# 	 Primary Neurites # 	 Neurite Order  	 Primary Neurites mean Length 	 Neurite Length 	 Longest Neurite Length 	 Axonal Tree length 	 Axonal Tree Branches #

Thanks in advance

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi SamN1985, 

I am sorry that you're facing this issue. I double checked by my side and the macro is running smoothly on my computer with the training images. Might be a very particular issue with your files. 
Could you send me the Stack_Body, Stack_BodySkelet, Stack_Neuron_Bin, Stack_Neuron_Original and Stack_NoBodySkelet files  in order to have a closer look.

During the mean time, you can try to restart Fiji and repeat the Part III or the macro from the begining.

Best regards.
Benoit

**Comment by SamN1985** [comment]
Dear Benoit
Thanks for replying! Here are the files. I've rerun the analysis with the
same error/result, hopefully it's just a small parameter that I am missing
that is easily corrected.

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello Sam, 
I am very sorry for the delay, I have been very busy these days... 
I do not see any file attached to your message... 
May be send them to me by email : boulan.benoit@gmail.com

Will do my best to trouble shot this issue asap.
regards, 
Benoit
