### ISSUE TITLE
The part I did not give the output

### ISSUE THREAD

**Issue by TranThiHang97** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#7]
Thank you for your great paper and instruction. I am trying to automatically measure the length of the axons and I found your paper. 
I followed the instruction in AutoNeuriteJ detailed protocol, but I was stuck at the AutoNeuriteJ part I. I did not measure the average diameter of nucleus (in pixels), and Check the pixel size of images (in μm) before running the macro because I am using your pictures so I keep the parameters that you set in the part I. However, after I run, it gave me a folder named "\resultats_AutoNeuriteJ-master\" as you described but there are no any files in that folders. I tried to run and run several times but no files showed up. 
Could you please help me? Thank you so much for your great support!
<img width="1440" alt="Screen Shot 2021-09-23 at 11 18 12" src="https://user-images.githubusercontent.com/81233041/134445796-e169aa2f-2221-4a24-ade3-101c5b1571aa.png">

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi TranThiHang97, 

First, thank you for your interest in our macro!
I am pretty sure that it's due to the fact you're running the macro on a MAC... 
I appologies for that, the macro was running fine on the MAC computer we tested before the publication but since then I have observed many issues using macro on MAC especially when the macro saves files on it... I think it's due to a "/" vs "\" for pathway assignement and that's why you see the "\" on your folder name... 

Could you use the macro on a PC ? I think it will be the quickest way for you to have this issue solved. 

Best regards, 
Benoit Boulan

**Comment by TranThiHang97** [comment]
Thank you so much for your prompt reply!
I understand the problem. I will test it in windows computer.
Thank you for your great support!
Yours Sincerely,
Tran Hang
