### ISSUE TITLE
Error in Part III

### ISSUE THREAD

**Issue by KatyRoq** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#8]
Hello, thanks for this great macro! I started by using the demo images, and everything from Part I and Part II worked perfectly. However, when I run part III (using default inputs), I am getting the following error:

Negative index in line 808
type_neurite [grand_neurite] <=>2

Please let me know if you can help with this issue. Alternately, I do not need all the functionality of this macro; I only need automated measurement of all neurite lengths. So please advise if there is an easy way to do this even if the neurite typing is not working properly. 

Thank you!
Katy

Here is the log:
 AutoNeuriteJ_Part III_settings : 
 minimal size of Axons (in pixels)=150
minimal size of Neurites (in pixels)=15
Axonal size ratio=1.5
Neurite Order : 1=axon / 2=primary neurite / 3=secondary neurite / 4=tertiary neurite ...

 Measures : 
Neuron# 	 Primary Neurites # 	 Neurite Order  	 Primary Neurites mean Length 	 Neurite Length 	 Longest Neurite Length 	 Axonal Tree length 	 Axonal Tree Branches #7

**Comment by KatyRoq** [comment]
Here is the debug file:
[Debug.csv](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/10462276/Debug.csv)

**Comment by hyjbcm** [comment]
I got the same error too

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi KatyRoq and hyjbcm, 

thank you for your interest in AutoneuriteJ. 
I am sorry that you encounter issues using the part III. 

It's the first time I ear about this problem, and can't reproduce it on my computer. 
@KatyRoq could you send me the folder containing the result files of the part II in order to me to try getting the same issue to troubleshoot it? 

Also are you using the Mac or the PC version of AutoneuriteJ ? 

Best regards, 
Benoit Boulan

**Comment by hyjbcm** [comment]
Hi Benoit, I used the PC version (My system is Windows 11 home), thank you

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi hyjbcm, 

I am currently using a Mac laptop so I will try on a computer. 
You actually could send me your part II output files as well. Since the issue is the same it could help me too. 

Best,
Benoit

**Comment by KatyRoq** [comment]
Hello Benoit, Thank you so much for your response. I was originally having the issue on PC, but I just tried it on a Mac and got the same error. I'm attaching the folder of results from Part II (PC). 

Thank you!
Katy

[r_Neuron_Demo-Image_Neurons_Cy3.zip](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/10481206/r_Neuron_Demo-Image_Neurons_Cy3.zip)

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello Katy, 

I am sorry I don't find the issue... your files are running with part III perfectly on my Mac as well as in a PC... 
One possibly that I could imagine is if you didn't install the different plugins necessary to run AutoneuriteJ (in particular "Analyze Skeleton 2D/3D") or  update them. 

Please let me know if it could be the case. 
Otherwise the last option I could propose is to setup a Visio meeting in order for me troubleshoot the issue in live while running AutoneuriteJ on your computer since it's running properly by my side...

Best regards,
Benoit

**Comment by KatyRoq** [comment]
Thanks for testing it, Benoit. 

I do have all the correct plugins installed. I have reproduced the same error on multiple Windows computers and a Mac, both in Fiji and ImageJ. I've also tried manually installing the plugins vs using the update site. 

I have used imagej for > 10 years and recently most new plugins I am testing are having errors, and one plugin that I used to run with no problem years ago is no longer working. While I understand that each plugin is developed independently, in my experience they all work extremely well, and this makes me wonder if there is a more general issue related to the Fiji version or the relatively recent update to java 8? What version of FIJI are you running? 

In terms of the exact error, which is "negative index in line 808" - is it a problem that the variable "neurite_majeur" has a value of -1 according to the debug file? 

The measurements that I need are only the number of neurites and neurite length for each cell. So for now I can run AnalyzeSkeleton plugin using the results of Part II of AutoneuriteJ. 

Thanks,
Katy

**Comment by KatyRoq** [comment]
In case it's relevant, I am also getting a couple console errors in Fiji. However they do not seem to affect most of the things I am using the software for.

1) When I initiate an update (see attached "update-error")
2) When I try to open the AutoneuriteJ macro via Plugins-->Macros-->Edit, ("edit-macro-error.txt). This only happened on PC

[edit-macro-error.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/10668673/edit-macro-error.txt)
[update-error.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/10668699/update-error.txt)

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi Katy, 

I am sorry that all your effort didn't gave any improvements... I don't think java 8 is the issue since I also tried on PC with Java8 installed in it.  And I hope this is not the problem since AutoneuriteJ is code in ImageJ language I actually don't have the knowledge to troubleshoot any java issue. 

However I realised that the line 702 in our code : `grand_neurite = -1; neurite_majeur=-1;`
could be the source of your problem. 
Please try to drag and drop AutoneuriteJ.ijm code on Fiji in order to get it open with the "Startup macro" window and edit the line 702 by : `grand_neurite = 0; neurite_majeur = 0;`

The macro still worked with this change on my computer so at least it should not raise any new error. 
I hope this will eventually solve your issue. 
Otherwise let me know and I will remove all the lines that compare neurites sizes to each others.

Best,
Benoit

**Comment by KatyRoq** [comment]
I made your suggested change in line 702, and it works perfectly! Thank you so much for your help!!
Katy

**Comment by Zblezble** [comment]
Hi Benoit,
just so you know it's not an isolated issue. I got the same error, while I was testing it with the provided demo files.
The change in line 702 fixed it for me just like for Katy.

Thanks for the great plugin!

Best,
David

**Comment by Grenoble-Institute-Neurosciences** [comment]
Thank you everyone for the feedback. 
I will change the line 702 in the master code so that it will be fine for everyone.

Best regards,
Benoit
