### ISSUE TITLE
Error code in part I

### ISSUE THREAD

**Issue by Zurflu** [Grenoble-Institute-Neurosciences/AutoNeuriteJ#9]
Hello,

I am trying to use the demo images provided to run through the macro. I am having issues in part I where I get the issue : original pixel size do not match with metadata value. please reset original pixel size in properties."

I am not sure how to reset the original pixel size properties. What I did before running the Macro:

1. opened DAPI image in image J >properties>checked pixel width (0.650µm)
2. measured using the drag straight line across a nucleus to get the pixel diameter
3. Opened macro> opened file containing images> entered pixel diameter got in 2. and changed pixel width to 0.650

This provided me with the above message and when I left the information as provided (1,cy3,1500,dapi, 
[Part I-settings_of_Neurite trial.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/10985909/Part.I-settings_of_Neurite.trial.txt)
30) I still got the error. I'm not sure how to proceed as I am fairly new to ImageJ.

Best,

Noah

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello Noah, 

yes this is something happening sometimes when for some weird reason ImageJ detect difference in between metadata of the image and the pixel size specified in part I. I think it's due to the writing of um vs µm something like that.

when the error occurs it open the setting window to change the pixel size value.
you can just ignore the error and let the pixel size at 0.650 µm which is the proper value. 
it do not impact the rest of the processing. 

Best, 
Benoit

**Comment by Zurflu** [comment]
Thank-you Benoit!

Now that I got past part I and II, I received an error message in Part III. "Negative index in line 1077. Type neurite [grand_neurite <=>2;]
[RoiSet.zip](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/11005948/RoiSet.zip)

Best,
Noah

**Comment by Zurflu** [comment]
Hello Benoit,

I have  changed the code as recommended below in a previous issue. 

The analysis works after changing it to 0 but I do not get any data for the axons. (length and branch number)
[Results.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/11062901/Results.txt)


-------------------
However I realized that the line 702 in our code : `grand_neurite = -1; neurite_majeur=-1;`
could be the source of your problem. 
Please try to drag and drop AutoneuriteJ.ijm code on Fiji in order to get it open with the "Startup macro" window and edit the line 702 by : `grand_neurite = 0; neurite_majeur = 0;`


The macro still worked with this change on my computer so at least it should not raise any new error. 

Best,
Benoit

_Originally posted by @Grenoble-Institute-Neurosciences in https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/issues/8#issuecomment-1419814264_

----------------------

Best,
Noah

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hello Noah,

I had a quick look on the result file you send me. The reason why you don't get any data for axonal tree length and branching is because AutoneuriteJ didn't detected any axones. If you look at the "Neurite Order" column there is no "1" value corresponding to axons.
With the parameter you used the macro will classified a neurite as an axon only if a primary neurite is at least 150um length AND if this primary neurite is at least 1,5 times longer than any other neurite of the neuron. It seems that in your neurones quantified this two criteria never happened.

Hope this helped...
Best,
Benoit

**Comment by Zurflu** [comment]
Hello Benoit,

I have tried various parameters to identify an axon  but am unable to accomplish it. I have reduced both the ratio and the minimum length of an axon with no luck.
[Part II-settings and neurons_count.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/11509999/Part.II-settings.and.neurons_count.txt)
[Results.txt](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/11510009/Results.txt)
[RoiSet.zip](https://github.com/Grenoble-Institute-Neurosciences/AutoNeuriteJ/files/11510014/RoiSet.zip)

Best,
Noah

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi Noah, 

Sorry for that... Looking at your Result file you should have some neurites assign as axons to me...
could you send me the output folder of part II ? 
It should be named something like "r_Neuron_20x H1 BDNF_488_C=0" in your case. 
I will try to run Part III on my computer to see what could happen. If it working for me we will double check that you have the same AutoneuriteJ version than me.

Best,
Benoit Boulan

**Comment by Zurflu** [comment]
Hello Benoit,

Thankyou for your help!
I am not able to attach the file in this chat as I get an error message saying github doesn't support the file type. Is there an alternative way I can send you the file? 

Best,
Noah

**Comment by Grenoble-Institute-Neurosciences** [comment]
Hi Noah, 
here is my email adress : benoit.boulan@ircm.qc.ca

Best regards, 
Benoit
